kibot:
  version: 1

global:
  output: '%f%r-%i.%x'

preflight:
  run_erc: true
  run_drc: true
  check_zone_fills: true
  ignore_unconnected: false

outputs:
  # For more information: https://github.com/INTI-CMNB/KiBoM
  - name: 'schematic-pdf'
    comment: "Print schematic (PDF)"
    type: pdf_sch_print
    dir: Schematics

  - name: 'schematic-svg'
    comment: "Print schematic (SVG)"
    type: svg_sch_print
    dir: Schematics/Sheets

  - name: 'print board mechanics'
    comment: "Print board layout (PDF)"
    type: pdf_pcb_print
    layers:
      - Dwgs.User
      - Edge.Cuts
      - F.CrtYd
    dir: Layout
    options:
    #  dnf_filter: ['exclude_dnp']
      drill_marks: full #[string='full'] what to use to indicate the drill places, can be none, small or full (for real scale).
#      mirror: [boolean=false] print mirrored (X axis inverted). ONLY for KiCad 6.
#      monochrome: [boolean=false] print in black and white.
      output: '%f%r-mechanic.%x' #[string='%f-%i%v.%x'] filename for the output PDF (%i=layers, %x=pdf). Affected by global options.
    #      output_name: Alias for output.
      plot_sheet_reference: true # [boolean=true] include the title-block.
    #      scaling: [number=1.0] scale factor (0 means autoscaling).
    #      separated: [boolean=false] print layers in separated pages.
    #      variant: [string=''] Board variant to apply.

  - name: 'print board documentation'
    comment: "Print board layout (PDF)"
    type: pdf_pcb_print
    layers: 
      - Edge.Cuts
      - Cmts.User
      - F.Fab
    dir: Layout
    options:
    #  dnf_filter: ['exclude_dnp']
    #      drill_marks: true #[string='full'] what to use to indicate the drill places, can be none, small or full (for real scale).
    #      mirror: [boolean=false] print mirrored (X axis inverted). ONLY for KiCad 6.
    #      monochrome: [boolean=false] print in black and white.
      output: '%f%r-documentation.%x' #[string='%f-%i%v.%x'] filename for the output PDF (%i=layers, %x=pdf). Affected by global options.
    #      output_name: Alias for output.
      plot_sheet_reference: true # [boolean=true] include the title-block.
    #      scaling: [number=1.0] scale factor (0 means autoscaling).
    #      separated: [boolean=false] print layers in separated pages.
    #      variant: [string=''] Board variant to apply.
