kibot:
  version: 1

global:
  output: '%f%r%v-%i.%x'
  variant: 'Default'

preflight:
  update_xml: true

outputs:
  - name: 'bom-interactive-html'
    comment: 'Generate interactive BOM (HTML)'
    type: 'ibom'
    dir: 'BOMs'
    options:
      checkboxes: 'Sourced,Placed'
      # [string=''] Comma separated list of extra fields to pull from netlist or xml file
      extra_fields: 'MPN,Assembly Notes'
      highlight_pin1: true
      include_nets: true
      include_tracks: true
      layer_view: 'FB'
      netlist_file: '%f/%f.xml'
      output: '%f%r%v-%i.%x'
      show_fabrication: true
      variant: 'Default'
