kibot:
  version: 1

preflight:
  update_xml: true
  run_drc: true
  check_zone_fills: true
  ignore_unconnected: true

filters:
  - name: 'exclude_dnp'
    type: 'generic'
    comment: 'Exclude components with value DNP'
    exclude_value: true
    keys: ['dnp', 'DNP']

outputs:
  - name: 'position'
    comment: 'Generate surface-mount positions for PCBWay (CSV)'
    type: 'position'
    dir: 'Assembly'
    options:
      dnf_filter: 'exclude_dnp'
      format: 'CSV'
      output: '%f%r-pos.%x'
      separate_files_for_front_and_back: false
      units: 'millimeters'
