kibot:
  version: 1

global:
  output: '%f%r%v-%i.%x'
  variant: 'Default'

preflight:
  run_erc: true

outputs:
  # For more information: https://github.com/INTI-CMNB/KiBoM
  - name: 'schematic-pdf'
    comment: "Print schematic (PDF)"
    type: pdf_sch_print
    dir: Schematics
    options:
      variant: 'Default'

  - name: 'schematic-svg'
    comment: "Print schematic (SVG)"
    type: svg_sch_print
    dir: Schematics/Images
    options:
      variant: 'Default'
