# Auto-generates exports for all KiCad projects

name: KiCad Exports

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    paths:
      - '**.sch'
      - '**.kicad_pcb'
  pull_request:
    paths:
      - '**.sch'
      - '**.kicad_pcb'
  milestone:
    types: [opened, deleted]
  workflow_dispatch:
    inputs:
      git-ref:
        description: 'Git ref (optional)'
        required: false

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  export:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Job environment variables
    env:
        board: ODSv1.0.0-PP-T41

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Auto-generates exports for KiCad5 projects
      - uses: nerdyscout/kicad-exports@v2.2
        with:
          # Required kibot config file
          config: docs.kibot.yaml
          # Optional prefix to output defined in config
          dir: ${{env.board}}/docs
          # Optional schematic file
          schema: ${{env.board}}/${{env.board}}.sch
          # Optional PCB design file
          board: ${{env.board}}/${{env.board}}.kicad_pcb

      # Uploads results as workflow artifacts
      - name: Upload results
        uses: actions/upload-artifact@v2
        with:
          name: docs
          path: ${{env.board}}/docs
