# Auto-generate exports for all KiCad projects

name: KiCad Exports

on:
  push:
  pull_request:
  milestone:
    types: [opened, deleted]
  workflow_dispatch:
    inputs:
      git-ref:
        description: 'Git ref (optional)'
        required: false

jobs:
  # Find changed boards
  generate-matrix:
    name: Generate matrix for exports
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{steps.set-matrix.outputs.matrix}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check changed files
        id: diff
        run: |
          # See https://github.community/t/check-pushed-file-changes-with-git-diff-tree-in-github-actions/17220/10
          if [ $GITHUB_BASE_REF ]; then
            # Pull Request
            git fetch origin $GITHUB_BASE_REF --depth=1
            export DIFF=$( git diff --name-only origin/$GITHUB_BASE_REF $GITHUB_SHA )
            echo "Diff between origin/$GITHUB_BASE_REF and $GITHUB_SHA"
          else
            # Push
            git fetch origin ${{ github.event.before }} --depth=1
            export DIFF=$( git diff --name-only ${{ github.event.before }} $GITHUB_SHA )
            echo "Diff between ${{ github.event.before }} and $GITHUB_SHA"
          fi
          echo "$DIFF"
          # Escape newlines (replace \n with %0A)
          echo "::set-output name=diff::$( echo "$DIFF" | sed ':a;N;$!ba;s/\n/%0A/g' )"

      - name: Set matrix for build
        id: set-matrix
        run: |
          # See https://stackoverflow.com/a/62953566/11948346
          DIFF="${{ steps.diff.outputs.diff }}"
          JSON="{\"board\":["

          # Loop by lines
          while read path; do
            # Set $directory to substring before /
            directory="$( echo $path | cut -d'/' -f1 -s )"

            if [ -z "$directory" ]; then
              continue # Exclude root directory
            elif [ "$directory" == Parts ]; then
              continue # Exclude Parts directory
            elif [ "$directory" == .github ]; then
              continue # Exclude .github directory
            fi

            # Add build to the matrix only if it is not already included
            JSONline="\"$directory\","
            if [[ "$JSON" != *"$JSONline"* ]]; then
              JSON="$JSON$JSONline"
            fi
          done <<< "$DIFF"

          # Remove last "," and add closing brackets
          if [[ $JSON == *, ]]; then
            JSON="${JSON%?}"
          fi
          JSON="$JSON]}"
          echo $JSON

          # Set output
          echo "::set-output name=matrix::$( echo "$JSON" )"

  # Export docs for changed boards
  export:
    name: Export docs for "${{matrix.board}}"
    needs: generate-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.generate-matrix.outputs.matrix)}}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Export docs
        uses: nerdyscout/kicad-exports@v2.2
        with:
          # Required kibot config file
          config: docs.kibot.yaml
          # Optional prefix to output defined in config
          dir: ${{matrix.board}}/docs
          # Optional schematic file
          schema: ${{matrix.board}}/${{matrix.board}}.sch
          # Optional PCB design file
          board: ${{matrix.board}}/${{matrix.board}}.kicad_pcb

      - name: Upload results
        uses: actions/upload-artifact@v2
        with:
          name: ${{matrix.board}}-docs
          path: ${{matrix.board}}/docs
