# Auto-generate exports for all KiCad projects

name: KiCad Exports

on:
  push:
    paths:
      - '*-*/**.sch'
      - '*-*/**.kicad_pcb'
      - '*-*/README.md'
      - '.github/workflows/kicad-exports.yml'
      - '.kibot/**'
  pull_request:
    paths:
      - '*-*/**.sch'
      - '*-*/**.kicad_pcb'
      - '*-*/README.md'
      - '.github/workflows/kicad-exports.yml'
      - '.kibot/**'
  milestone:
    types: [opened, deleted]
  workflow_dispatch:
    inputs:
      git-ref:
        description: 'Git ref (optional)'
        required: false

jobs:
  # Find changed boards
  generate-matrix:
    name: Generate matrix for exports
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{steps.set-matrix.outputs.matrix}}
      numboards: ${{steps.set-matrix.outputs.numboards}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check changed files
        id: diff
        run: |
          # See https://github.community/t/check-pushed-file-changes-with-git-diff-tree-in-github-actions/17220/10
          if [ $GITHUB_BASE_REF ]; then
            # Pull Request
            git fetch origin $GITHUB_BASE_REF --depth=1
            export DIFF=$( git diff --name-only origin/$GITHUB_BASE_REF $GITHUB_SHA )
            echo "Diff between origin/$GITHUB_BASE_REF and $GITHUB_SHA:"
          else
            # Push
            git fetch origin ${{ github.event.before }} --depth=1
            export DIFF=$( git diff --name-only ${{ github.event.before }} $GITHUB_SHA )
            echo "Diff between ${{ github.event.before }} and $GITHUB_SHA:"
          fi
          echo "$DIFF"
          # Treat all directories as changed if this workflow is changed
          if echo "$DIFF" | grep -q '.github/workflows/kicad-exports.yml'; then
            export DIFF=$( ls -d */ )
          elif  echo "$DIFF" | grep -q '.kibot/config'; then
            export DIFF=$( ls -d */ )
          fi
          # Escape newlines (replace \n with %0A)
          echo "::set-output name=diff::$( echo "$DIFF" | sed ':a;N;$!ba;s/\n/%0A/g' )"

      - name: Set matrix for build
        id: set-matrix
        run: |
          # See https://stackoverflow.com/a/62953566/11948346
          DIFF="${{ steps.diff.outputs.diff }}"
          JSON="{\"board\":["
          NUMBOARDS=0

          # Loop by lines
          while read path; do
            # Set $directory to substring before /
            directory="$( echo $path | cut -d'/' -f1 -s )"

            if [ -z "$directory" ]; then
              continue # Exclude root directory
            elif [ "$directory" == Parts ]; then
              continue # Exclude Parts directory
            elif [ "$directory" == .github ]; then
              continue # Exclude .github directory
            fi

            # Add build to the matrix only if it is not already included
            JSONline="\"$directory\","
            if [[ "$JSON" != *"$JSONline"* ]]; then
              JSON="$JSON$JSONline"
              NUMBOARDS=$((NUMBOARDS+1))
            fi
          done <<< "$DIFF"

          # Remove last "," and add closing brackets
          if [[ $JSON == *, ]]; then
            JSON="${JSON%?}"
          fi
          JSON="$JSON]}"
          echo $JSON
          echo $NUMBOARDS

          # Set output
          echo "::set-output name=matrix::$( echo "$JSON" )"
          echo "::set-output name=numboards::$( echo "$NUMBOARDS" )"

  # Export docs for changed boards
  export:
    name: Export docs for ${{matrix.board}}
    needs: generate-matrix
    runs-on: ubuntu-latest
    if: needs.generate-matrix.outputs.numboards > 0
    strategy:
      matrix: ${{fromJson(needs.generate-matrix.outputs.matrix)}}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Export docs
        uses: nerdyscout/kicad-exports@v2.2
        with:
          # Required kibot config file
          config: '.kibot/config/docs.kibot.yaml'
          # Optional prefix to output defined in config
          dir: ${{matrix.board}}/docs
          # Optional schematic file
          schema: ${{matrix.board}}/${{matrix.board}}.sch
          # Optional PCB design file
          board: ${{matrix.board}}/${{matrix.board}}.kicad_pcb

      - name: Get layout version
        id: version
        run: |
          REVISION=$(grep -o '(rev .*)' ${{matrix.board}}/${{matrix.board}}.kicad_pcb)
          VERSION=$(echo $REVISION | sed -E 's/\(rev (.*)\)/\1/')
          echo "::set-output name=layout::$(echo "$VERSION")"

      - name: Postprocess DRC report
        working-directory: ${{matrix.board}}/docs/
        run: |
          sudo mv drc_result.rpt "${{matrix.board}}${{steps.version.outputs.layout}}-drc.log"
          sudo mv ${{matrix.board}}.erc "${{matrix.board}}${{steps.version.outputs.layout}}-erc.log"

      - name: Copy README and LICENSEs
        run: |
          sudo cp LICENSE* ${{matrix.board}}/docs/
          sudo cp ${{matrix.board}}/README.md ${{matrix.board}}/docs/

      - name: Get current date
        id: date
        run: echo "::set-output name=today::$(date +'%Y%m%d')"

      - name: Upload results
        uses: actions/upload-artifact@v2
        with:
          name: ${{matrix.board}}${{steps.version.outputs.layout}}-docs-rev${{steps.date.outputs.today}}
          path: ${{matrix.board}}/docs
